version: '3.7'

services:
  api:
    build:
      context: .
      target: development
    container_name: clean-arch-api
    image: clean-arch-api:latest
    user: '1000:1000'
    volumes:
      - .:/usr/src/app
    networks:
      - clean-arch-network
    # env_file: '.env.dev'
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: postgres:11.9
    container_name: clean-arch-db
    ports:
      - 5432:5432
    networks:
      - clean-arch-network
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: clean-arch-db

  pgadmin:
    image: dpage/pgadmin4:4.30
    container_name: clean-arch-pgadmin
    ports:
      - 6400:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - clean-arch-network
    depends_on:
      - db

networks:
  clean-arch-network:
    driver: bridge

volumes:
  pgadmin:
    driver: local
